# Generated by Django 5.1.5 on 2025-02-18 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_contactus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='description',
            new_name='message',
        ),
    ]
