# Generated by Django 5.1.5 on 2025-02-18 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0005_rename_description_contactus_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='user',
        ),
        migrations.AddField(
            model_name='contactus',
            name='email',
            field=models.CharField(default='lorem@gmail.com', max_length=200),
        ),
        migrations.AddField(
            model_name='contactus',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
